version: '3.3'

services:
  postgres:
    image: postgres:15-alpine
    container_name: 'hospital-db'

    ports:
      - "5432:1432"
    environment:
      POSTGRES_DB: hospital
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    user: "postgres"
  java:
    build: ./
    container_name: 'hospital-java'
    ports:
      - "8081:9090"
    depends_on:
      - postgres
volumes:
  postgres_data: